# Rate limiting
# ------------------------------------------------------------ #

map $ratelimit $ratelimit_state {
    0  "";
    1  $binary_remote_addr;
}
limit_conn_status 429;
limit_req_status 429;
limit_req_zone $ratelimit_state zone=engintron_req_zone:10m rate=1r/s;
