# Rate limiting
# ------------------------------------------------------------ #

# Custom 429 error page
error_page 429 = @ratelimit;
location @ratelimit {
    internal;
    default_type text/html;
    return 429 '<!doctype html><html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>Rate limit exceeded</title><style type="text/css">body {font-family:Helvetica, Arial, sans-serif;font-size:1rem;color:#fff;padding:0;margin:0;text-align:center;background:radial-gradient(ellipse at center, rgb(82 115 195) 0%, rgb(0 0 0) 100%);height:100vh;display:flex;align-content:center;align-items:center;justify-content:center;}h1 {font-size:3rem;line-height:130%;padding:0;margin:0;}p {line-height:150%;}a {color:#eee;text-decoration:none;font-weight:bold;}a:hover {color:#fff;}hr {display:block;height:0;padding:0;margin:15px 0;border-top:1px solid #162f6d;}#container {padding:30px;}</style></head><body><div id="container"><h1>Rate limit exceeded</h1><p><a href="/">The website</a> is currently protected with connection rate limiting.</p><p>You will return to the page you visited in 5 seconds...</p></div><script>var url = window.location.href;if (url.indexOf("ref=429") < 0) {Error_429_Refresh = window.setTimeout(function(){if (url.indexOf("?") > 0) {window.location.href = window.location.href + "&ref=429";} else {window.location.href = window.location.href + "?ref=429";}}, 5*1000);}</script></body></html>';
    add_header Retry-After 5 always;
}

# Define rate limiting settings
limit_req zone=engintron_req_zone burst=5 nodelay;

# Rate limiting enabled
set $ratelimit 1;

# Exclusion for homepages
if ($request_uri = "/") {
    set $ratelimit 0;
}

# Exclusions for Joomla
if ($request_uri ~* "^/administrator/|format=json|format=raw|^/images/|^/media/|^/templates") {
    set $ratelimit 0;
}

# Exclusions for WordPress/WooCommerce
if ($request_uri ~* "^/cart/|^/checkout/|^/\?wc-ajax=|^/wp-admin/|^/wp-content/|^/wp-json/") {
    set $ratelimit 0;
}

# Exclusions for Drupal
if ($http_cookie ~* "SESS[a-zA-Z0-9_]+") {
    set $ratelimit 0;
}
if ($request_uri ~* "^/admin|/ajax/|^/status\.php|^/system/files/|^/update\.php|^/user") {
    set $ratelimit 0;
}

# Exclusions for static files (match against $uri to avoid issues with query strings)
if ($uri ~* "\.(?:css|js|json|svg|svgz|txt|xml|avif|ico|jpg|jpeg|gif|png|webp|avi|m4v|mkv|mov|mp4|mpeg|mpg|ogm|ogv|webm|wmv|woff|woff2)$") {
    set $ratelimit 0;
}

# Exclusions for bots
if ($http_user_agent ~* "googlebot|facebookexternalhit|meta-external|Microsoft\.News\.Ingestion|SkroutzBot|Skroutz ImageBot|WP Rocket/Preload") {
    set $ratelimit 0;
}
